version: '3'

networks:
  produto_net:
    driver: bridge

volumes:
  kubedevnews:
  pgadmin-data:

services:
  postgres:
    image: postgres:14.5
    ports:
      - 5432:5432
    networks:
      - produto_net
    volumes:
      - kubedevnews:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kubedevnews
      - POSTGRES_PASSWORD=Pg#123
      - POSTGRES_DB=kubedevnews
  node:
    image: harrisonlima/kube-news:v1
    networks:
      - produto_net
    depends_on:
      - postgres
    ports:
      - 8080:8080
  pgadmin:
    image: dpage/pgadmin4:6.15
    ports:
      - 80:80
    networks:
      - produto_net
    depends_on:
      - postgres
      - node
    environment:
      - PGADMIN_DEFAULT_EMAIL=postuser@postuser.com
      - PGADMIN_DEFAULT_PASSWORD=postpwd
    volumes:
      - pgadmin-data:/var/lib/pgadmin